-- AlterTable
ALTER TABLE `Class` ADD COLUMN `createdAt` DATETIME(3) NULL DEFAULT CURRENT_TIMESTAMP(3),
    ADD COLUMN `day` VARCHAR(191) NULL,
    ADD COLUMN `hour` VARCHAR(191) NULL,
    ADD COLUMN `maxStudent` INTEGER NULL,
    ADD COLUMN `updatedAt` DATETIME(3) NULL;
